"""Adicionando forma de pagamento

Revision ID: c67f5de3d942
Revises: 41671b9d7dea
Create Date: 2025-03-03 18:32:02.897231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67f5de3d942'
down_revision = '41671b9d7dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('forma_pagamento')

    # ### end Alembic commands ###
