"""Adicionando campos de contato e último pagamento

Revision ID: e959cd1e57fa
Revises: d30892399f18
Create Date: 2025-03-03 22:45:14.413332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e959cd1e57fa'
down_revision = 'd30892399f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None):
        op.add_column('user', sa.Column('contato', sa.String(150), nullable=False, server_default=''))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contato')

    # ### end Alembic commands ###
